# Generated by Django 5.2.5 on 2025-09-23 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('margherita_poli', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectionexhibition',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RenameModel(
            old_name='SectionDrawing',
            new_name='SectionPainting',
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='margherita_poli/files/painting')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='margherita_poli.sectionpainting')),
            ],
        ),
        migrations.DeleteModel(
            name='Drawing',
        ),
    ]
