# Generated by Django 5.2.5 on 2025-09-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('margherita_poli', '0002_alter_poem_date_alter_sectionexhibition_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
