# Generated by Django 5.2.5 on 2025-10-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('margherita_poli', '0003_painting_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo_it', models.CharField(max_length=200, verbose_name='Titolo (Italiano)')),
                ('titolo_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Titolo (Inglese)')),
                ('contenuto_it', models.TextField(verbose_name='Contenuto (Italiano)')),
                ('contenuto_en', models.TextField(blank=True, null=True, verbose_name='Contenuto (Inglese)')),
            ],
        ),
    ]
