# Generated by Django 5.2.5 on 2025-11-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('margherita_poli', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='painting',
            name='title_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
