# Generated by Django 5.2.5 on 2025-11-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('margherita_poli', '0005_painting_description_en_painting_title_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionpainting',
            name='section_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
