# Generated by Django 5.2.5 on 2025-11-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('margherita_poli', '0006_sectionpainting_section_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionpainting',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectionpainting',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
