# Generated by Django 5.2.5 on 2025-11-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('margherita_poli', '0007_sectionpainting_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionpainting',
            name='description',
            field=models.TextField(blank=True, default='Nessuna descrizione disponibile', null=True),
        ),
        migrations.AlterField(
            model_name='sectionpainting',
            name='description_en',
            field=models.TextField(blank=True, default='Nessuna descrizione disponibile', null=True),
        ),
    ]
