# Generated by Django 5.2.5 on 2025-11-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('margherita_poli', '0008_alter_sectionpainting_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='italic_title',
            field=models.BooleanField(default=False, verbose_name='Titolo in corsivo'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='painting',
            name='description_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='painting',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sectionpainting',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sectionpainting',
            name='description_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sectionpainting',
            name='section_en',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
    ]
