# Generated by Django 5.2.5 on 2025-11-08 13:54

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('margherita_poli', '0009_painting_italic_title_alter_painting_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painting',
            name='italic_title',
        ),
        migrations.AlterField(
            model_name='painting',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='painting',
            name='description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='painting',
            name='title',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='painting',
            name='title_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sectionpainting',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sectionpainting',
            name='description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sectionpainting',
            name='section',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sectionpainting',
            name='section_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', max_length=50),
        ),
    ]
