# Generated by Django 5.2.5 on 2025-11-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('margherita_poli', '0010_remove_painting_italic_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='painting',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='sectionpainting',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='painting',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Ordine di visualizzazione'),
        ),
        migrations.AddField(
            model_name='sectionpainting',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
