# Generated by Django 5.2.5 on 2025-11-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('margherita_poli', '0011_alter_painting_options_alter_sectionpainting_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='margherita_poli/files/painting'),
        ),
    ]
