# Generated by Django 5.2.5 on 2025-11-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('margherita_poli', '0012_alter_painting_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poem',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='poem',
            name='poem',
        ),
        migrations.AddField(
            model_name='poem',
            name='image',
            field=models.ImageField(default='', upload_to='margherita_poli/files/poem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poem',
            name='date',
            field=models.DateField(),
        ),
    ]
