# Generated by Django 5.2.5 on 2025-11-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('margherita_poli', '0013_alter_poem_options_remove_poem_poem_poem_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibition',
            name='section',
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='image',
            field=models.ImageField(upload_to='margherita_poli/files/exhibition'),
        ),
        migrations.DeleteModel(
            name='SectionExhibition',
        ),
    ]
