# Generated by Django 5.2.5 on 2025-11-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('margherita_poli', '0014_remove_exhibition_section_alter_exhibition_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Illustration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='margherita_poli/files/illustration')),
            ],
        ),
        migrations.DeleteModel(
            name='Exhibition',
        ),
    ]
