# Generated by Django 5.2.5 on 2025-11-12 08:54

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('margherita_poli', '0015_illustration_delete_exhibition'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionExhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', django_ckeditor_5.fields.CKEditor5Field(default='', max_length=50)),
                ('section_en', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', max_length=50)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='')),
                ('description_en', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', django_ckeditor_5.fields.CKEditor5Field(default='', max_length=50)),
                ('title_en', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', max_length=50)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='')),
                ('description_en', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='margherita_poli/files/exhibition')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordine di visualizzazione')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='margherita_poli.sectionexhibition')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
