# Generated by Django 5.2.5 on 2025-11-12 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('margherita_poli', '0016_sectionexhibition_exhibition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibition',
            name='description',
        ),
        migrations.RemoveField(
            model_name='exhibition',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='exhibition',
            name='price',
        ),
        migrations.RemoveField(
            model_name='exhibition',
            name='title',
        ),
        migrations.RemoveField(
            model_name='exhibition',
            name='title_en',
        ),
    ]
