# Generated by Django 5.2.5 on 2025-11-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('margherita_poli', '0017_remove_exhibition_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='illustration',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='illustration',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Ordine di visualizzazione'),
        ),
    ]
