# Generated by Django 5.2.5 on 2025-11-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('margherita_poli', '0018_alter_illustration_options_illustration_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='status',
            field=models.CharField(choices=[('available', 'Disponibile'), ('sold', 'Venduto'), ('not_for_sale', 'Non in vendita')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='painting',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
