# Generated by Django 5.2.5 on 2025-11-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('margherita_poli', '0019_painting_status_alter_painting_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='custom_price_text',
            field=models.CharField(blank=True, help_text="Se lo status è 'Testo personalizzato', questo verrà mostrato", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='painting',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='painting',
            name='status',
            field=models.CharField(choices=[('available', 'Disponibile'), ('sold', 'Venduto'), ('not_for_sale', 'Non in vendita'), ('custom', 'Testo personalizzato')], default='available', max_length=20),
        ),
    ]
