# Generated by Django 5.2.5 on 2025-11-13 10:42

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('margherita_poli', '0020_painting_custom_price_text_alter_painting_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='details',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='painting',
            name='details_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default=''),
        ),
    ]
