# Generated by Django 5.2.5 on 2025-11-15 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('margherita_poli', '0021_painting_details_painting_details_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='custom_price_text_en',
            field=models.CharField(blank=True, help_text="'Custom text'", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='painting',
            name='custom_price_text',
            field=models.CharField(blank=True, help_text="'Testo personalizzato'", max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='CheckoutOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'In attesa'), ('confirmed', 'Confermato'), ('cancelled', 'Cancellato')], default='pending', max_length=20)),
                ('painting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='margherita_poli.painting')),
            ],
        ),
    ]
