# Generated by Django 5.2.5 on 2025-11-19 08:26

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('margherita_poli', '0022_painting_custom_price_text_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_address', models.CharField(max_length=200)),
                ('customer_city', models.CharField(max_length=100)),
                ('customer_region', models.CharField(max_length=100)),
                ('customer_zip', models.CharField(max_length=10)),
                ('customer_country', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'In attesa'), ('paid', 'Pagato'), ('failed', 'Fallito')], default='pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_intent_id', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sectionexhibition',
            name='section',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='sectionexhibition',
            name='section_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', max_length=60),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='margherita_poli.order')),
                ('painting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='margherita_poli.painting')),
            ],
        ),
        migrations.DeleteModel(
            name='CheckoutOrder',
        ),
    ]
