# Generated by Django 5.2.5 on 2025-11-19 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('margherita_poli', '0024_contactmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'Messaggio ricevuto', 'verbose_name_plural': 'Messaggi ricevuti'},
        ),
    ]
